MODEL:
  WEIGHT: "imagenet"
  FREEZE: False
  VISUAL_MODEL: "resnet50"
  TEXTUAL_MODEL: "bigru"
  NUM_CLASSES: 11003
  NUM_PARTS: 5
  LSTM:
    EMBEDDING_SIZE: 512
    NUM_UNITS: 512
    VOCABULARY_SIZE: 12000
    DROPOUT_KEEP_PROB: 1.0
    MAX_LENGTH: 100
  RESNET:
    RES5_STRIDE: 1
  EMBEDDING:
    EMBED_HEAD: 'segpool'
    FEATURE_SIZE: 256
    DROPOUT_PROB: 0.0
    K_RECIPROCAL: False
INPUT:
  HEIGHT: 384
  WIDTH: 128
  USE_AUG: True
  DOWNSAMPLE_RATIO: 0.0625
DATASETS:
  TRAIN: ("cuhkpedes_train", )
  TEST: ("cuhkpedes_test", )
  BIN_SEG: True
SOLVER:
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 80
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.00004
  CHECKPOINT_PERIOD: 40
  LRSCHEDULER: 'step'
  STEPS: (40, 70)
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
