MODEL:
  WEIGHT: "imagenet"
  FREEZE: False
  VISUAL_MODEL: "resnet50"
  TEXTUAL_MODEL: "bert"
  NUM_CLASSES: 11003
  NUM_PARTS: 5
  RESNET:
    RES5_STRIDE: 1
  EMBEDDING:
    EMBED_HEAD: 'simple'
    FEATURE_SIZE: 256
    DROPOUT_PROB: 0.0
INPUT:
  HEIGHT: 384
  WIDTH: 128
  USE_AUG: True
DATASETS:
  TRAIN: ("cuhkpedes_train", )
  TEST: ("cuhkpedes_test", )
  USE_ONEHOT: False
  USE_SEG: False
  USE_ATT: False
SOLVER:
  OPTIMIZER: "AdamW"
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 60
  BASE_LR: 0.00011
  WEIGHT_DECAY: 0.00004
  CHECKPOINT_PERIOD: 60
  LRSCHEDULER: 'step'
  GAMMA: 0.9
  STEPS: (20, 30, 40)
  PART_STRATEGRY: True
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
