MODEL:
  WEIGHT: "imagenet"
  FREEZE: True
  VISUAL_MODEL: "vit_deit_small_patch16_224"
  TEXTUAL_MODEL: "bilstm"
  NUM_CLASSES: 11003
  NUM_PARTS: 5
  LSTM:
    EMBEDDING_SIZE: 512
    NUM_UNITS: 512
    VOCABULARY_SIZE: 12000
    DROPOUT_KEEP_PROB: 1.0
    MAX_LENGTH: 100
  EMBEDDING:
    EMBED_HEAD: 'simple'
    FEATURE_SIZE: 256
    DROPOUT_PROB: 0.0
  VIT:
    CKPT: "pretrained/deit_small_market.pth"
INPUT:
  HEIGHT: 256
  WIDTH: 128
  USE_AUG: True
DATASETS:
  TRAIN: ("cuhkpedes_train", )
  TEST: ("cuhkpedes_test", )
  USE_SEG: FALSE
  USE_ATT: FALSE
SOLVER:
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 80
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.00004
  CHECKPOINT_PERIOD: 80
  LRSCHEDULER: 'step'
  STEPS: (40, 70)
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
