MODEL:
  NUM_CLASSES: 11003
  EMBEDDING:
    EMBED_HEAD: 'clip'
    FEATURE_SIZE: 1024
INPUT:
  HEIGHT: 224
  WIDTH: 224
  USE_AUG: False
DATALOADER:
  EN_SAMPLER: True
DATASETS:
  TRAIN: ("cuhkpedes_train", )
  TEST: ("cuhkpedes_test", )
  USE_SEG: FALSE
  USE_ATT: FALSE
  USE_ONEHOT: FALSE
SOLVER:
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 80
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  CHECKPOINT_PERIOD: 40
  LRSCHEDULER: 'step'
  STEPS: (40, 70)
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
